---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no   # runs the "setup" module on remote hosts
  connection: ansible.builtin.ssh   # default connection type

  vars:
    mission_data: # [{"mission": "primary", "planet": "luna park"}, {"mission": "secondary", "planet": "cineplex 14"}]
      - mission: primary
        planet: luna park
      - mission: secondary
        planet: cineplex 14

  vars_files:
    - vars/planetexpress.yml

  tasks:
    #  - name: test our loop
    #  debug:
    #    var: item.mission
    #  loop: "{{ mission_data }}"
    - debug:
        var: planet

  # the first one should be titled primary-mission-orders.txt
  # the second secondary-mission-orders.txt
    - name: Configure mission orders
      ansible.builtin.template:
        src: templates/mission-orders.txt.j2
        dest: "~/{{ item.mission }}-mission-orders.txt"
      loop: "{{ mission_data }}"



